    <!-- Form contact -->
<div class="header_title">
  <h1 class="container head_title" style="text-align: center;">Terms and Conditions & Privacy Policy</h1>
</div>
<div class="container auth">

    

    <div id="big-form" class="well auth-box" style="text-align: justify; font-size: 17px;">
    	
    	<p>
 We are committed to protecting your privacy and securing your information. Please read our full privacy policy below.
This privacy statement applies to Lendexsys.com owned and operated by Lendexsys Inc. LLC (“Lendexsys.com”, “we”, “us”, “our”). This privacy statement describes how Lendexsys Inc. LLC collects and uses the personal information you provide on our website: Lendexsys.com. It also describes the choices available to you regarding our use of your personal information and how you can access and update this information.</p>

<h4 style="font-weight: 600; font-size: 18px;">This website uses Google Adwords</h4>
<p>This website uses the Google AdWords remarketing and customer match services to exclude advertising on third party websites (including Google) to previous site visitors or site users.
It could mean that we EXCLUDE advertisements to previous visitors on our site. This could be in the form of excluding an advertisement on the Google search results page or a site in the Google Display Network. Third-party vendors, including Google, use cookies to serve or exclude ads based on someone’s past visits to this website. Of course, any data collected will be used in accordance with our own privacy policy and Google’s privacy policy.
It could also mean that we EXCLUDE advertisements to previous applicants that have submitted their email address to us for the purpose of obtaining or using or services offered on our websites
AdWords remarketing will allow us to not display ads to you based on what parts of this website you have viewed by placing a cookie on your machine or not display ads if you are logged in to any google services by using your email address to exclude advertisements to you using the Google Adwords customer match service.</p>

<h4 style="font-weight: 600; font-size: 18px;">This cookie does not in anyway identify you or give access to your computer.</h4>
<p>Google AdWords Remarketing allows us to tailor our marketing to better suit your needs and only display ads that are relevant to you. As always we respect your privacy and are not collecting any identifiable information through the use of Google’s or any other 3rd party remarketing system.
In addition to using cookies and related technologies as described above, we also may permit certain third party companies to help us tailor advertising that we think may be of interest to users and to collect and use other data about user activities on our Sites and/or Services (e.g., to allow them to tailor ads to third-party services). These companies may deliver ads that might also place cookies and otherwise track user behavior.
You can set preferences for how Google advertises to you using the Google Ad Preferences page, and if you want to you can opt out of interest-based advertising entirely by cookie settings or permanently using a browser plugin.</p>

<h4 style="font-weight: 600; font-size: 18px;">Personal Information</h4>
<p>By submitting your personal information, you understand and agree such personal information (including the Sensitive Information) may be shared with third-parties, including without limitation, Loan Providers in order to complete your request for Loan Products and/or other marketing purposes. We reserve the right to share, rent, sell or otherwise disclose your information with/to third parties in accordance with applicable laws and as described herein. These third party businesses may include, but are not limited to: consumer reporting agencies, consumer credit bureaus, financial service providers, Loan Providers, providers of direct marketing services and applications, including lookup and reference, data enhancement, suppression, and validation; e-mail marketers; wireless services providers and telemarketers. Furthermore, you authorize us to use any information collected from you to obtain other information about you from third-parties, such as your social security number, where such information was incompletely or improperly filled out on our registration form. Third–parties may also use your personal information for any lawful purposes, subject to any restrictions contained herein. Any information that you supply to any third-party or Loan Provider shall be governed by the applicable third party’s or Loan Providers’ Privacy Policies. Any and all information that we collect from you and from any third-party may be used to determine your eligibility for any product, service or offer.</p>
<p>	Please be advised that Lendexsys.com does not itself provide Loan Products, Services, Brokering or Customer Service related to any application submitted by you, or any other related products and/or services. The ultimate terms and conditions of any Loan Products and Information provided by any Loan Providers will be determined by those Loan Providers.
Please note: by submitting your personal information, your information is being provided by you freely. You further agree to receive marketing offers from us or third-party marketers, that we or they may believe may be of interest to you, and you expressly consent and agree to be contacted through but not limited to the following methods: (a) direct mail marketing; (b) e-mail marketing; (c) telemarketing calls (where permitted by applicable law); (d) SMS text-based messages (where permitted by applicable law); and (e) any other manner contemplated herein. By using this Website, you agree that you may be contacted in any manner contemplated in this section, even if your number is found on a do-not-call registry or similar registry.
We may also use personal information for website administrative customer service, to provide our visitors with information which may be requested, to customize visitor experiences on the Site, and for internal business purposes, such as analyzing and managing our business. Third parties may be used to assist in the operation of this Site or to administer activities on our behalf. These companies are authorized to use your personal information only as necessary to provide these services to us.
</p>
<p>We specifically reserve the right to release current or past user information, as it is made available to us from third-parties, in the event the user is using or has used, our products, services and/or Site: (i) in violation of the Site’s Terms and Conditions, this Privacy Statement or any of our operating rules, policies, and/or other supplemental terms and conditions or documents that may be published from time to time; (ii) to commit unlawful acts; (iii) if such information is subpoenaed or requested pursuant to a judicial or regulatory proceeding or inquiry or similar legal process; when we believe in good faith that disclosure is necessary to protect our rights, protect your safety or the safety of others, investigate fraud, or respond to a government request (iv) if this Site is sold or acquired, you will be notified via email and/or a prominent notice on our Web site of any change in ownership or uses of your personal information, as well as any choices you may have regarding your personal information; and/or (v) when deemed necessary or appropriate including, without limitation to, sharing your e-mail address with other third parties for suppression purposes in compliance with the CAN-SPAM Act of 2003, as amended from time to time, and Federal Trade Commission implementing regulations.</p>
<p>By registering, you agree that such act constitutes an inquiry and/or application for purposes of the Amended Telemarketing Sales Rule (16 CFR 310 et seq.), as amended from time to time (the “Rule”) and applicable state do-not-call regulations. As such, notwithstanding that your telephone number may be listed on the Federal Trade Commission’s Do-Not-Call List, and/or on applicable federal or state do-not-call lists, we retain the right to contact you via telemarketing in accordance with the Rule and applicable state do-not-call regulations.</p>
<p>In addition, by submitting your personal information, you agree to receive mobile marketing including, but not limited to, text-message based marketing, from us and our third-party advertisers and marketers (where, and to the extent that, such marketing is permitted by applicable law). You further agree that based on your individual carrier and plan, you may incur charges associated with such SMS Messages and that you agree to be solely responsible for such charges. You represent that you are at least 18 years of age and the owner or authorized user of the wireless device on which messages will be received and that you are authorized to approve the applicable charges. Should you hereafter choose to opt-out of receiving SMS Messages from the individual sender, you may opt-out by texting “STOP” or “OPT-OUT” as specifically set forth in the communication. Notwithstanding that your mobile telephone number may be listed on state and/or federal do-not-call registries, we retain the right to contact you via SMS Messages. In addition, by registering and/or using the Website, you agree that such act constitutes an inquiry and/or application for purposes of the Amended Telemarketing Sales Rule (16 CFR 310 et seq.), as amended from time to time. As such, notwithstanding that your mobile telephone number may be listed on state and/or federal Do-Not-Call registries, we retain the right to contact you via text-message based marketing in accordance with applicable state and federal law. Further, you agree that we reserve the right to share, sell, rent, lease and/or otherwise distribute your mobile telephone and other mobile data with/to any third-party for any and all non-marketing uses permitted by this Privacy Statement and applicable law.
Without limiting the generality of the foregoing, we reserve the right to share, sell, rent, lease and/or otherwise distribute any and all personal information (other than the Sensitive Information) with/to any third party for any and all uses permitted by this Privacy Statement and applicable law.
If you have questions or concerns regarding this statement, you should first contact <a href="mailto:customers@lendexsys.com">customers@Lendexsys.com</a>. Lendexsys Inc. LLC is committed to protecting your privacy when you visit our website. You can access Lendexsys.com and browse our site without disclosing any of your personal information.</p>
<h4 style="font-weight: 600; font-size: 18px;">Non-Personal Information</h4>
<p>We may also use your IP addresses to compile and provide aggregate statistics about our visitors, traffic patterns, and administer and improve the site. This statistical information may also be related to third parties, track user’s movement, and gather demographic and profile information for aggregate use. We may also use third-party analytics services to record information, including without limitation, mouse clicks, mouse movements, and scrolling activity as well as text you type in the Website, which may be used by us or third-parties to understand how users interact with the site.</p>
<h4 style="font-weight: 600; font-size: 18px;">Access to Personal Information</h4>
<p>If your personal information changes, or if you no longer desire our service, you may correct, update, delete your information by emailing our Customer Support at <a href="mailto:customers@lendexsys.com">customers@Lendexsys.com</a>, or by contacting us by telephone or postal mail at the contact information listed below. We will respond to your request within a reasonable timeframe.</p>
<h4 style="font-weight: 600; font-size: 18px;">Our Commitment to Children’s Privacy</h4>
<p>Protecting the privacy of young children is important to us. For that reason, we do not collect or maintain information from those believed or actually known to be under 18 years of age, and no part of our site is structured to attract anyone under 18 years of age.</p>
<h4 style="font-weight: 600; font-size: 18px;">Email Campaigns</h4>
We use your e-mail address to send you newsletters, and other customer-related material.
Lendexsys.com has a zero-tolerance policy for e-mail abuse. If you receive unsolicited e-mails from Lendexsys.com please report it to us at <a href="mailto:customers@lendexsys.com">customers@Lendexsys.com</a>.
    </div>

    <div class="clearfix"></div>

  </div>

<!-- Form contact -->